#include <iostream>
#include <vector>

#pragma once

struct MusicKit_t
{
    uint16_t id;
    std::string name;
    std::string image_url = "";
    
    MusicKit_t(uint16_t _id, std::string _name, std::string _img = "") : id(_id), name(_name), image_url(_img) {}
};

enum class MusicKit : uint16_t
{
    CounterStrike2 = 1,
    MusicNotNamed,
    CrimsonAssault,
    Sharpened,
    Insurgency,
    A_D_8,
    HighNoon,
    DeathsHeadDemolition,
    DesertFire,
    LNOE,
    Metal,
    AllIWantForChristmas,
    IsoRhythm,
    ForNoMankind,
    HotlineMiami,
    The8BitKit,
    TheTalosPrinciple,
    Battlepack,
    Molotov,
    UberBlastoPhone,
    HazardousEnvironments,
    Headshot,
    TotalDomination,
    IAm,
    Diamonds,
    Invasion,
    LionsMouth,
    SpongeFingerz,
    Aggressive,
    JavaHavanaFunkaloo,
    MomentsCSGO,
    Disgusting,
    TheGoodYouth,
    Free,
    LifesNotOutToGetYou,
    Backbone,
    GLA,
    Arena,
    EZ4ENCE,
    Halo,
    KingScar,
    AlxyAntiCitizen,
    Bachram,
    TacoTruck,
    EyeOfTheDragon,
    MUDDForce,
    NeoNoir,
    Bodacious,
    Drifter,
    AllForDust,
    Hades,
    TheLowfilePack,
    ChainsawLxadxut,
    MochaPetal,
    YellowMagic,
    Vici,
    AtroBellum,
    WorkHardPlayHard,
    Kolibri,
    U_Mad,
    FlashBangDance,
    HeadingForTheSource,
    Void,
    Shooters,
    Dashstar,
    GothicLuxury,
    LockMeUp,
    HuaLian,
    Ultimate,
    CSGO,
    UnderBrightLights = 76
};

std::vector<MusicKit_t> musicKits =
{
    { MusicKit_t(static_cast<uint16_t>(MusicKit::CounterStrike2),        "Counter-Strike 2") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MusicNotNamed),         "Valve CSGO 2 (hidden)") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::CrimsonAssault),        "Crimson Assault") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Sharpened),             "Sharpened") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Insurgency),            "Insurgency") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::A_D_8),                 "A_D_8") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HighNoon),              "High Noon") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::DeathsHeadDemolition),  "Death's Head Demolition") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::DesertFire),            "Desert Fire") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LNOE),                  "LNOE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Metal),                 "Metal") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AllIWantForChristmas),  "All I Want For Christmas") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::IsoRhythm),             "Iso Rhythm") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ForNoMankind),          "For No Mankind") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HotlineMiami),          "Hotline Miami") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::The8BitKit),            "The 8-Bit Kit") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheTalosPrinciple),     "The Talos Principle") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Battlepack),            "Battlepack") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Molotov),               "Molotov") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::UberBlastoPhone),       "Uber Blasto Phone") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HazardousEnvironments), "Hazardous Environments") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Headshot),              "Headshot") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TotalDomination),       "Total Domination") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::IAm),                   "I Am") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Diamonds),              "Diamonds") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Invasion),              "Invasion!") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LionsMouth),            "Lion's Mouth") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::SpongeFingerz),         "Sponge Fingerz") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Aggressive),            "Aggressive") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::JavaHavanaFunkaloo),    "Java Havana Funkaloo") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MomentsCSGO),           "Moments CSGO") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Disgusting),            "Disgusting") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheGoodYouth),          "The Good Youth") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Free),                  "FREE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LifesNotOutToGetYou),   "Life's Not Out To Get You") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Backbone),              "Backbone") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::GLA),                   "GLA") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Arena),                 "Arena") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::EZ4ENCE),               "EZ4ENCE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Halo),                  "Halo") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::KingScar),              "King, Scar") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AlxyAntiCitizen),       "Anti-Citizen") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Bachram),               "Bachram") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TacoTruck),             "Taco Truck") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::EyeOfTheDragon),        "Eye of the Dragon") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MUDDForce),             "M.U.D.D. FORCE") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::NeoNoir),               "Neo Noir") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Bodacious),             "Bodacious") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Drifter),               "Drifter") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AllForDust),            "All For Dust") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Hades),                 "Hades") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::TheLowfilePack),        "The Lowfile Pack") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::ChainsawLxadxut),       "CHAINSAW Lxadxut") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::MochaPetal),            "Mocha Petal") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::YellowMagic),           "Yellow Magic") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Vici),                  "VICI") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::AtroBellum),            "Atro Bellum") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::WorkHardPlayHard),      "Work Hard, Play Hard") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Kolibri),               "Kolibri") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::U_Mad),                 "U Mad!") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::FlashBangDance),        "Flashbang Dance") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HeadingForTheSource),   "Heading For The Source") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Void),                  "Void") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Shooters),              "Shooters") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Dashstar),              "Dashstar*")},
    { MusicKit_t(static_cast<uint16_t>(MusicKit::GothicLuxury),          "Gothic Luxury") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::LockMeUp),              "Lock Me Up") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::HuaLian),               "Hua Lian") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::Ultimate),              "Ultimate") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::UnderBrightLights),     "Under Bright Lights") },
    { MusicKit_t(static_cast<uint16_t>(MusicKit::CSGO),                  "CS:GO") }
};